# Generated by Django 6.0.3 on 2026-03-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_categoriaitem_item_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo_aprobado', '✅ Préstamo Aprobado'), ('prestamo_rechazado', '❌ Préstamo Rechazado'), ('prestamo_vence_hoy', '⚠️ Vence Hoy'), ('prestamo_atrasado', '🔴 Préstamo Atrasado'), ('cambio_aceptado', '🔄 Cambio Aceptado'), ('recordatorio', '🔔 Recordatorio')], max_length=30, verbose_name='Tipo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accounts.prestamo', verbose_name='Préstamo relacionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
